from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional

router = APIRouter()


class ReferralRequest(BaseModel):
    childId: str
    screeningId: str


class ReferralPdfRequest(BaseModel):
    childId: str
    referralId: str
    letterText: str


@router.post("/generate-referral")
async def generate_referral(request: ReferralRequest):
    """
    Generate a clinical referral letter using Gemini Pro.
    TODO: Integrate google-generativeai in Phase 3.
    """
    # Placeholder — will use Gemini Pro to generate the letter
    letter_text = (
        f"Clinical Referral Letter\n\n"
        f"Child ID: {request.childId}\n"
        f"Based on screening {request.screeningId}, "
        f"this child requires further audiological evaluation.\n\n"
        f"This referral was generated by HearTech AI screening system.\n"
        f"Please conduct a comprehensive hearing assessment.\n"
    )

    return {
        "letterText": letter_text,
        "childId": request.childId,
        "screeningId": request.screeningId,
    }


@router.post("/generate-referral-pdf")
async def generate_referral_pdf(request: ReferralPdfRequest):
    """
    Generate PDF from referral letter using ReportLab, upload to Cloudinary.
    TODO: Implement ReportLab PDF generation and Cloudinary upload in Phase 3.
    """
    # Placeholder
    return {
        "pdfUrl": "https://placeholder.com/referral.pdf",
        "referralId": request.referralId,
    }
