import 'dart:io';
import 'package:dio/dio.dart';

/// Service to handle file uploads to Cloudinary (free tier).
/// Used as a zero-cost replacement for Firebase Storage.
class CloudinaryService {
  // To avoid exposing secrets in client, we use unsigned upload
  // with an upload preset configured in Cloudinary dashboard.
  // For HearTech demo, these are placeholder values that will need actual config.
  final String _cloudName = 'heartech-demo';
  final String _uploadPreset = 'heartech_unsigned';

  /// Upload a file to Cloudinary and return the secure URL.
  Future<String?> uploadFile(File file, {required String folder}) async {
    try {
      final dio = Dio();
      final formData = FormData.fromMap({
        'file': await MultipartFile.fromFile(file.path),
        'upload_preset': _uploadPreset,
        'folder': folder,
      });

      final response = await dio.post(
        'https://api.cloudinary.com/v1_1/$_cloudName/upload',
        data: formData,
      );

      if (response.statusCode == 200) {
        return response.data['secure_url'] as String;
      }
      return null;
    } catch (e) {
      print('Cloudinary Upload Error: $e');
      return null;
    }
  }

  /// Helper to upload medical licenses (HCW)
  Future<String?> uploadLicense(File file) {
    return uploadFile(file, folder: 'licenses');
  }

  /// Helper to upload profile photos
  Future<String?> uploadProfilePhoto(File file) {
    return uploadFile(file, folder: 'profiles');
  }

  /// Helper to upload referral PDFs generated by FastAPI
  Future<String?> uploadReferralPdf(File file) {
    return uploadFile(file, folder: 'referrals');
  }
}
