// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKWzWvMIOpl6Bz_vr_bYgmX9OC3JAP3-M',
    appId: '1:569550695748:web:c4aa4c19d41ce3d0c2bb11',
    messagingSenderId: '569550695748',
    projectId: 'heartech-fyp',
    authDomain: 'heartech-fyp.firebaseapp.com',
    storageBucket: 'heartech-fyp.firebasestorage.app',
    measurementId: 'G-4682V09Y8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC121uJ7jLQdTAbS4rXcF1mnFvh0w_f7Y0',
    appId: '1:569550695748:android:8a8eff97dfbefa84c2bb11',
    messagingSenderId: '569550695748',
    projectId: 'heartech-fyp',
    storageBucket: 'heartech-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5jeyUhrW-BVkJSWhoFaA3v8hPy2KQSHg',
    appId: '1:569550695748:ios:ce0a21586a7566b6c2bb11',
    messagingSenderId: '569550695748',
    projectId: 'heartech-fyp',
    storageBucket: 'heartech-fyp.firebasestorage.app',
    iosClientId: '569550695748-39svpm1fg779pe55bjmoqcmkfordl1dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5jeyUhrW-BVkJSWhoFaA3v8hPy2KQSHg',
    appId: '1:569550695748:ios:ce0a21586a7566b6c2bb11',
    messagingSenderId: '569550695748',
    projectId: 'heartech-fyp',
    storageBucket: 'heartech-fyp.firebasestorage.app',
    iosClientId: '569550695748-39svpm1fg779pe55bjmoqcmkfordl1dv.apps.googleusercontent.com',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKWzWvMIOpl6Bz_vr_bYgmX9OC3JAP3-M',
    appId: '1:569550695748:web:7b91e08f6e930a19c2bb11',
    messagingSenderId: '569550695748',
    projectId: 'heartech-fyp',
    authDomain: 'heartech-fyp.firebaseapp.com',
    storageBucket: 'heartech-fyp.firebasestorage.app',
    measurementId: 'G-9029SFPQ9S',
  );

}