// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6IsCQyGNc3FoJzP50GV5a1GcmIPT7_2I',
    appId: '1:922824594006:web:2aa2aac435e323c952a1f7',
    messagingSenderId: '922824594006',
    projectId: 'heartech-eea27',
    authDomain: 'heartech-eea27.firebaseapp.com',
    storageBucket: 'heartech-eea27.firebasestorage.app',
    measurementId: 'G-66BJ8Q4CWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuNvYbUpATI1hO83dR2acktZTKan3tUR4',
    appId: '1:922824594006:android:c1f9e891550003ce52a1f7',
    messagingSenderId: '922824594006',
    projectId: 'heartech-eea27',
    storageBucket: 'heartech-eea27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmHpBRVjxOJWCZ1CooYZDfVcbdajr7vU',
    appId: '1:922824594006:ios:830543f33f3463cb52a1f7',
    messagingSenderId: '922824594006',
    projectId: 'heartech-eea27',
    storageBucket: 'heartech-eea27.firebasestorage.app',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmHpBRVjxOJWCZ1CooYZDfVcbdajr7vU',
    appId: '1:922824594006:ios:830543f33f3463cb52a1f7',
    messagingSenderId: '922824594006',
    projectId: 'heartech-eea27',
    storageBucket: 'heartech-eea27.firebasestorage.app',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6IsCQyGNc3FoJzP50GV5a1GcmIPT7_2I',
    appId: '1:922824594006:web:892052cd952cb04f52a1f7',
    messagingSenderId: '922824594006',
    projectId: 'heartech-eea27',
    authDomain: 'heartech-eea27.firebaseapp.com',
    storageBucket: 'heartech-eea27.firebasestorage.app',
    measurementId: 'G-H111WBV19Q',
  );
}
