// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuL91E4Afs9ZnqWdxtI38iqskdqyt2beM',
    appId: '1:10963670501:web:ba6b7607531f27c314cb0c',
    messagingSenderId: '10963670501',
    projectId: 'heartech-7db7f',
    authDomain: 'heartech-7db7f.firebaseapp.com',
    storageBucket: 'heartech-7db7f.firebasestorage.app',
    measurementId: 'G-NKGJB8MY8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1eVyKuu1iM3vqKWwL670NDpTrZAYGAY8',
    appId: '1:10963670501:android:d7b5b0fe56a2ee8c14cb0c',
    messagingSenderId: '10963670501',
    projectId: 'heartech-7db7f',
    storageBucket: 'heartech-7db7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoA6keoJPQor8djquX0Y_EtYikzYOdE3U',
    appId: '1:10963670501:ios:8b6b34555eebce9114cb0c',
    messagingSenderId: '10963670501',
    projectId: 'heartech-7db7f',
    storageBucket: 'heartech-7db7f.firebasestorage.app',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoA6keoJPQor8djquX0Y_EtYikzYOdE3U',
    appId: '1:10963670501:ios:8b6b34555eebce9114cb0c',
    messagingSenderId: '10963670501',
    projectId: 'heartech-7db7f',
    storageBucket: 'heartech-7db7f.firebasestorage.app',
    iosBundleId: 'com.example.heartech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuL91E4Afs9ZnqWdxtI38iqskdqyt2beM',
    appId: '1:10963670501:web:3e4fcf3522c3ee9714cb0c',
    messagingSenderId: '10963670501',
    projectId: 'heartech-7db7f',
    authDomain: 'heartech-7db7f.firebaseapp.com',
    storageBucket: 'heartech-7db7f.firebasestorage.app',
    measurementId: 'G-LZMXT7X2ZC',
  );
}
